name: movie_app_with_clean_architecture
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
